// Code generated by protoc-gen-go. DO NOT EDIT.
// source: vehicle.proto

/*
Package vehicle is a generated protocol buffer package.

It is generated from these files:
	vehicle.proto

It has these top-level messages:
	VehicleRequest
	VehicleErrorResponse
*/
package vehicle

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type VehicleRequest struct {
	ID        int64  `protobuf:"varint,1,opt,name=ID,json=iD" json:"ID,omitempty"`
	VIN       string `protobuf:"bytes,2,opt,name=VIN,json=vIN" json:"VIN,omitempty"`
	Make      string `protobuf:"bytes,3,opt,name=Make,json=make" json:"Make,omitempty"`
	Model     string `protobuf:"bytes,4,opt,name=Model,json=model" json:"Model,omitempty"`
	Color     string `protobuf:"bytes,5,opt,name=Color,json=color" json:"Color,omitempty"`
	Type      string `protobuf:"bytes,6,opt,name=Type,json=type" json:"Type,omitempty"`
	Condition string `protobuf:"bytes,7,opt,name=Condition,json=condition" json:"Condition,omitempty"`
}

func (m *VehicleRequest) Reset()                    { *m = VehicleRequest{} }
func (m *VehicleRequest) String() string            { return proto.CompactTextString(m) }
func (*VehicleRequest) ProtoMessage()               {}
func (*VehicleRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *VehicleRequest) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *VehicleRequest) GetVIN() string {
	if m != nil {
		return m.VIN
	}
	return ""
}

func (m *VehicleRequest) GetMake() string {
	if m != nil {
		return m.Make
	}
	return ""
}

func (m *VehicleRequest) GetModel() string {
	if m != nil {
		return m.Model
	}
	return ""
}

func (m *VehicleRequest) GetColor() string {
	if m != nil {
		return m.Color
	}
	return ""
}

func (m *VehicleRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *VehicleRequest) GetCondition() string {
	if m != nil {
		return m.Condition
	}
	return ""
}

type VehicleErrorResponse struct {
	ID      int64  `protobuf:"varint,1,opt,name=ID,json=iD" json:"ID,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=Message,json=message" json:"Message,omitempty"`
}

func (m *VehicleErrorResponse) Reset()                    { *m = VehicleErrorResponse{} }
func (m *VehicleErrorResponse) String() string            { return proto.CompactTextString(m) }
func (*VehicleErrorResponse) ProtoMessage()               {}
func (*VehicleErrorResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *VehicleErrorResponse) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *VehicleErrorResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*VehicleRequest)(nil), "vehicle.VehicleRequest")
	proto.RegisterType((*VehicleErrorResponse)(nil), "vehicle.VehicleErrorResponse")
}

func init() { proto.RegisterFile("vehicle.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 221 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0xbf, 0x6a, 0xc3, 0x30,
	0x10, 0xc6, 0xf1, 0xbf, 0x18, 0x1d, 0x34, 0x14, 0x91, 0xe1, 0x86, 0x0e, 0x21, 0x53, 0xa6, 0x2e,
	0x7d, 0x81, 0xd2, 0xa4, 0x83, 0x07, 0x67, 0x10, 0x25, 0x43, 0x37, 0xd7, 0x39, 0x5a, 0x11, 0xdb,
	0xa7, 0x4a, 0x6a, 0x20, 0xef, 0xd3, 0x07, 0x2d, 0x92, 0x9c, 0xa9, 0xdb, 0xfd, 0x7e, 0xc7, 0x07,
	0xdf, 0x1d, 0xdc, 0x5d, 0xe8, 0x4b, 0xf7, 0x03, 0x3d, 0x1a, 0xcb, 0x9e, 0x65, 0x3d, 0xe3, 0xe6,
	0x37, 0x83, 0xe5, 0x31, 0xcd, 0x8a, 0xbe, 0x7f, 0xc8, 0x79, 0xb9, 0x84, 0xbc, 0xd9, 0x63, 0xb6,
	0xce, 0xb6, 0x85, 0xca, 0xf5, 0x5e, 0xde, 0x43, 0x71, 0x6c, 0x0e, 0x98, 0xaf, 0xb3, 0xad, 0x50,
	0xc5, 0xa5, 0x39, 0x48, 0x09, 0x65, 0xdb, 0x9d, 0x09, 0x8b, 0xa8, 0xca, 0xb1, 0x3b, 0x93, 0x5c,
	0x41, 0xd5, 0xf2, 0x89, 0x06, 0x2c, 0xa3, 0xac, 0xc6, 0x00, 0xc1, 0xee, 0x78, 0x60, 0x8b, 0x55,
	0xb2, 0x7d, 0x80, 0x90, 0x7f, 0xbb, 0x1a, 0xc2, 0x45, 0xca, 0xfb, 0xab, 0x21, 0xf9, 0x00, 0x62,
	0xc7, 0xd3, 0x49, 0x7b, 0xcd, 0x13, 0xd6, 0x71, 0x21, 0xfa, 0x9b, 0xd8, 0x3c, 0xc3, 0x6a, 0x6e,
	0xf9, 0x6a, 0x2d, 0x5b, 0x45, 0xce, 0xf0, 0xe4, 0xe8, 0x5f, 0x57, 0x84, 0xba, 0x25, 0xe7, 0xba,
	0x4f, 0x9a, 0xfb, 0xd6, 0x63, 0xc2, 0x17, 0xf1, 0x7e, 0xbb, 0xf9, 0x63, 0x11, 0x7f, 0xf0, 0xf4,
	0x17, 0x00, 0x00, 0xff, 0xff, 0xa8, 0xf6, 0xb7, 0xa6, 0x14, 0x01, 0x00, 0x00,
}
